
package org.example.web4;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "web4", targetNamespace = "http://www.example.org/web4/", wsdlLocation = "file:/C:/eclipse/space/Stress-test/web4client/resources/web4.wsdl")
public class Web4_Service
    extends Service
{

    private final static URL WEB4_WSDL_LOCATION;
    private final static WebServiceException WEB4_EXCEPTION;
    private final static QName WEB4_QNAME = new QName("http://www.example.org/web4/", "web4");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/eclipse/space/Stress-test/web4client/resources/web4.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEB4_WSDL_LOCATION = url;
        WEB4_EXCEPTION = e;
    }

    public Web4_Service() {
        super(__getWsdlLocation(), WEB4_QNAME);
    }

    public Web4_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEB4_QNAME, features);
    }

    public Web4_Service(URL wsdlLocation) {
        super(wsdlLocation, WEB4_QNAME);
    }

    public Web4_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEB4_QNAME, features);
    }

    public Web4_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Web4_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Web4
     */
    @WebEndpoint(name = "service4")
    public Web4 getService4() {
        return super.getPort(new QName("http://www.example.org/web4/", "service4"), Web4.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Web4
     */
    @WebEndpoint(name = "service4")
    public Web4 getService4(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/web4/", "service4"), Web4.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEB4_EXCEPTION!= null) {
            throw WEB4_EXCEPTION;
        }
        return WEB4_WSDL_LOCATION;
    }

}
