
package org.example.web4;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "web4", targetNamespace = "http://www.example.org/web4/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Web4 {


    /**
     * 
     * @param in
     * @return
     *     returns javax.xml.ws.Response<org.example.web4.NewOperationResponse>
     */
    @WebMethod(operationName = "NewOperation", action = "http://www.example.org/web4/NewOperation")
    @RequestWrapper(localName = "NewOperation", targetNamespace = "http://www.example.org/web4/", className = "org.example.web4.NewOperation")
    @ResponseWrapper(localName = "NewOperationResponse", targetNamespace = "http://www.example.org/web4/", className = "org.example.web4.NewOperationResponse")
    public Response<NewOperationResponse> newOperationAsync(
        @WebParam(name = "in", targetNamespace = "")
        int in);

    /**
     * 
     * @param in
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "NewOperation", action = "http://www.example.org/web4/NewOperation")
    @RequestWrapper(localName = "NewOperation", targetNamespace = "http://www.example.org/web4/", className = "org.example.web4.NewOperation")
    @ResponseWrapper(localName = "NewOperationResponse", targetNamespace = "http://www.example.org/web4/", className = "org.example.web4.NewOperationResponse")
    public Future<?> newOperationAsync(
        @WebParam(name = "in", targetNamespace = "")
        int in,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<NewOperationResponse> asyncHandler);

    /**
     * 
     * @param in
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "NewOperation", action = "http://www.example.org/web4/NewOperation")
    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "NewOperation", targetNamespace = "http://www.example.org/web4/", className = "org.example.web4.NewOperation")
    @ResponseWrapper(localName = "NewOperationResponse", targetNamespace = "http://www.example.org/web4/", className = "org.example.web4.NewOperationResponse")
    public String newOperation(
        @WebParam(name = "in", targetNamespace = "")
        int in);

}
